volumes:
 mssql-data:
 
networks:
 backend-network:
 proxy-network:

services:
 db:
   container_name: testpoint-database
   image: mcr.microsoft.com/mssql/server:2022-latest
   restart: always
   environment:
     MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD}
     ACCEPT_EULA: "Y"
     TZ: ${TIMEZONE}
   volumes:
     - mssql-data:/var/opt/mssql
   ports:
     - "1433:1433"
   networks:
     - backend-network
 redis:
   container_name: testpoint-redis
   image: redis
   restart: always
   ports:
     - "6379:6379"
   networks:
     - backend-network
 backend:
   container_name: testpoint-backend
   image: denleo/testpoint-backend:latest
   restart: always
   environment:
     TZ: ${TIMEZONE}
     ASPNETCORE_ENVIRONMENT: Production
     HOST: "172.104.135.55"
     HTTP_PORT: "8081"
     HTTPS_PORT: "8080"
   depends_on:
     - db
     - redis
   networks:
     - backend-network
     - proxy-network
 client:
   container_name: testpoint-client
   image: denleo/testpoint-client:latest
   restart: always
   depends_on:
     - backend
   networks:
     - proxy-network
 proxy:
   container_name: testpoint-proxy
   image: denleo/testpoint-proxy:latest
   restart: always
   ports:
     - "8080:443"
     - "8081:80"
   depends_on:
     - client
     - backend
   networks:
     - proxy-network
