name: Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  build-api:
    timeout-minutes: 5
    name: build-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./API
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal