name: Deploy (to Linode)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            cd ~/TestPoint
            git pull
            docker rmi --force denleo/testpoint-proxy:latest || true
            docker rmi --force denleo/testpoint-client:latest || true
            docker rmi --force denleo/testpoint-backend:latest || true
            docker-compose -f docker-compose.prod.yml up -d --force-recreate