name: Push

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - main

jobs:
  build-api:
    timeout-minutes: 5
    name: build-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: API
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  
  docker-push:
    needs: build-api
    name: docker-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker login
        env:
          USER: ${{secrets.DOCKER_USERNAME}}
          PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u "$USER" -p "$PASSWORD"
      - name: Build images
        run: docker-compose build --no-cache
      - name: Push images
        run: docker-compose push